version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: my-very-strong-password
    volumes:
      - /mnt/rbd/postgres/data:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ads23@example.com
      PGADMIN_DEFAULT_PASSWORD: my-very-strong-password
    volumes:
      - /mnt/rbd/postgres/pgadmin:/var/lib/pgadmin
